apiVersion: v1
kind: Service
metadata:
  name: credit-check-service
spec:
  selector:
    app: credit-check-service
  ports:
    - name: http
      protocol: TCP
      port: 8888
      targetPort: 8888
  type: NodePort
